### ISSUE TITLE
Module not found when running mkdocs serve

### ISSUE THREAD

**Issue by Maxiride** [facelessuser/pymdown-extensions#110]
I'm using mkdocs, and I would like to use emojis in it with your plugin, however the emoji module is not found by the system.

I've added the required code in the `mkdocs.yml`:
```
- pymdownx.emoji:
      emoji_generator: !!python/name:pymdownx.emoji.to_svg

```

I've also installed python-markdown:
```bash
$ pip install pymdown-extensions
Collecting pymdown-extensions
  Using cached pymdown_extensions-4.0-py2.py3-none-any.whl
Collecting Markdown<3,>=2.6.0 (from pymdown-extensions)
Installing collected packages: Markdown, pymdown-extensions
Successfully installed Markdown-2.6.9 pymdown-extensions-4.0
```

However when running `mkdocs serve` for a loca live preview I get in console the following erros that sums up in **module not found**:

```bash
$ mkdocs serve
INFO    -  Building documentation... 
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/yaml/constructor.py", line 521, in find_python_name
    __import__(module_name)
ImportError: No module named 'pymdownx'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/bin/mkdocs", line 9, in <module>
    load_entry_point('mkdocs==0.14.0', 'console_scripts', 'mkdocs')()
  File "/usr/lib/python3/dist-packages/click/core.py", line 716, in __call__
    return self.main(*args, **kwargs)
  File "/usr/lib/python3/dist-packages/click/core.py", line 696, in main
    rv = self.invoke(ctx)
  File "/usr/lib/python3/dist-packages/click/core.py", line 1060, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/lib/python3/dist-packages/click/core.py", line 889, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/lib/python3/dist-packages/click/core.py", line 534, in invoke
    return callback(*args, **kwargs)
  File "/usr/lib/python3/dist-packages/mkdocs/cli.py", line 112, in serve_command
    livereload=livereload,
  File "/usr/lib/python3/dist-packages/mkdocs/serve.py", line 78, in serve
    config = builder()
  File "/usr/lib/python3/dist-packages/mkdocs/serve.py", line 71, in builder
    theme=theme,
  File "/usr/lib/python3/dist-packages/mkdocs/config/base.py", line 143, in load_config
    cfg.load_file(config_file)
  File "/usr/lib/python3/dist-packages/mkdocs/config/base.py", line 96, in load_file
    return self.load_dict(utils.yaml_load(config_file))
  File "/usr/lib/python3/dist-packages/mkdocs/utils/__init__.py", line 58, in yaml_load
    return yaml.load(source, Loader)
  File "/usr/lib/python3/dist-packages/yaml/__init__.py", line 72, in load
    return loader.get_single_data()
  File "/usr/lib/python3/dist-packages/yaml/constructor.py", line 37, in get_single_data
    return self.construct_document(node)
  File "/usr/lib/python3/dist-packages/yaml/constructor.py", line 46, in construct_document
    for dummy in generator:
  File "/usr/lib/python3/dist-packages/yaml/constructor.py", line 398, in construct_yaml_map
    value = self.construct_mapping(node)
  File "/usr/lib/python3/dist-packages/yaml/constructor.py", line 204, in construct_mapping
    return super().construct_mapping(node, deep=deep)
  File "/usr/lib/python3/dist-packages/yaml/constructor.py", line 129, in construct_mapping
    value = self.construct_object(value_node, deep=deep)
  File "/usr/lib/python3/dist-packages/yaml/constructor.py", line 88, in construct_object
    data = constructor(self, tag_suffix, node)
  File "/usr/lib/python3/dist-packages/yaml/constructor.py", line 537, in construct_python_name
    return self.find_python_name(suffix, node.start_mark)
  File "/usr/lib/python3/dist-packages/yaml/constructor.py", line 524, in find_python_name
    "cannot find module %r (%s)" % (module_name, exc), mark)
yaml.constructor.ConstructorError: while constructing a Python object
cannot find module 'pymdownx.emoji' (No module named 'pymdownx')
  in "/home/federico/Projects/example-bot-docs/mkdocs.yml", line 24, column 24
```

**Comment by facelessuser** [comment]
There is quite a lot I don't know, so it makes it hard for me to tell what the issue is.  As I use mkdocs, mkdocs-material, and pymdown-extensions for all of my projects (especially pymdown-extensions), I can assure you it does work, so I am immediately suspicious of your local environment.

Do you have multiple instances of Python installed?  Are you sure that when you run `pip install` and `mkdocs serve` that the same version of Python is running in those two cases? I mention this because I have run into issues like this before which causes me to now run `python3 -m pip install` and `python3 -m mkdocs serve` to ensure that I am installing the the modules into the version of Python I think I am, and running the mkdocs in the version I think I am.

**Comment by Maxiride** [comment]
After further investigation, you are right @facelessuser! The issue is indeed due to the setup.

[I've installed mkdocs via apt and the plugin via pip ](https://github.com/mkdocs/mkdocs/issues/1281#issuecomment-328894909), is there a workaround to keep using mkdocs from the apt repo?

**Comment by facelessuser** [comment]
Don't use apt, but use pip to install all of your python modules.  Apt is fine for installing Python itself, and possibly even pip for the Python in your Linux distro, but I never use apt to manage my Python module installations.

**Comment by Maxiride** [comment]
Ok thank you very much, purged the apt mkdocs installation and used pip!

I would like to take the occasion to ask another think, how can I change the emoji provider from the yml configuration file?

**Comment by facelessuser** [comment]
This is covered in the documenation: http://facelessuser.github.io/pymdown-extensions/extensions/emoji/#default-emoji-indexes

You can select one of the 3 provided emoji providers: Gemoji (GitHub's), EmojiOne, or Twemoji (Twitter's).  You can also write your own index for some other provider.

Remember though that you need to specify them just as a function using the function notation of PyYaml: https://github.com/facelessuser/pymdown-extensions/blob/master/tests/extensions/emoji/tests.yml#L77.

**Comment by Maxiride** [comment]
Suberb. Thank you very much for your time and your excellent plugin! :+1:

**Comment by facelessuser** [comment]
No problem.  Glad you enjoy the plugin :slightly_smiling_face:.

**Comment by VNAPNIC** [comment]
u don't run "pip install pymdown-extensions" before using markdown_extensions

**Comment by noahfranco** [comment]
I installed `pip install pymdown-extensions` now I can run `mkdocs build` without any problems. Thank you 👍

**Comment by YumekaMengjiaLYU** [comment]
For those who tried `pip install pymdown-extensions` but failed,  `pip install mkdocs-material-extensions` enabled me to `mkdocs build`.

**Comment by rogelio-bg** [comment]
I had the same issue, ran `pip install pymdown-extensions` and `pip install mkdocs-material-extensions` and none of them worked, until I ran `pip install mkdocs-material`

**Comment by mirmahfuz99** [comment]
Ensure that you have the materialx module installed. You can install it using the following command:

`pip install mkdocs-material`
