### ISSUE TITLE
TypeError from improper indentation when superfences is enabled

### ISSUE THREAD

**Issue by seancolsen** [facelessuser/pymdown-extensions#2148]
### Description

I found a piece of markdown content that appears to cause pymdown-extensions to raise an unhandled exception.

> TypeError: cannot unpack non-iterable NoneType object

This causes my MkDocs site to choke during build.

I'm able to work around this issue by fixing my content. But I wanted to report this as a bug nonetheless.

### Minimal Reproduction

1. Begin an mkdocs site with the following content:

    - `mkdocs.yml`

        ```yml
        site_name: Foo

        markdown_extensions:
          - pymdownx.superfences
        ```

    - `docs/index.md`

        ```md
        1. Foo
            <details>
              <summary>Summary 1</summary>
          
                Content 1
            </details>
          <details>
              <summary>Summary 2</summary>
          
                Content 2
            </details>
        ```

        Note the malformed indentation above. The second opening `<details>` tag is not indented enough.

1. Run `mkdocs serve`

1. Expect the site to build.

1. Instead, observe the following output containing a traceback.

    <details>
    <summary>Output</summary>

    ```
    INFO     -  Building documentation...
    INFO     -  Cleaning site directory
    ERROR    -  Error reading page 'index.md': cannot unpack non-iterable NoneType object
    Traceback (most recent call last):
      File "/home/sean/.local/bin/mkdocs", line 8, in <module>
        sys.exit(cli())
      File "/usr/lib/python3/dist-packages/click/core.py", line 1128, in __call__
        return self.main(*args, **kwargs)
      File "/usr/lib/python3/dist-packages/click/core.py", line 1053, in main
        rv = self.invoke(ctx)
      File "/usr/lib/python3/dist-packages/click/core.py", line 1659, in invoke
        return _process_result(sub_ctx.command.invoke(sub_ctx))
      File "/usr/lib/python3/dist-packages/click/core.py", line 1395, in invoke
        return ctx.invoke(self.callback, **ctx.params)
      File "/usr/lib/python3/dist-packages/click/core.py", line 754, in invoke
        return __callback(*args, **kwargs)
      File "/home/sean/.local/lib/python3.10/site-packages/mkdocs/__main__.py", line 234, in serve_command
        serve.serve(dev_addr=dev_addr, livereload=livereload, watch=watch, **kwargs)
      File "/home/sean/.local/lib/python3.10/site-packages/mkdocs/commands/serve.py", line 83, in serve
        builder(config)
      File "/home/sean/.local/lib/python3.10/site-packages/mkdocs/commands/serve.py", line 76, in builder
        build(config, live_server=live_server, dirty=dirty)
      File "/home/sean/.local/lib/python3.10/site-packages/mkdocs/commands/build.py", line 308, in build
        _populate_page(file.page, config, files, dirty)
      File "/home/sean/.local/lib/python3.10/site-packages/mkdocs/commands/build.py", line 181, in _populate_page
        page.render(config, files)
      File "/home/sean/.local/lib/python3.10/site-packages/mkdocs/structure/pages.py", line 270, in render
        self.content = md.convert(self.markdown)
      File "/home/sean/.local/lib/python3.10/site-packages/markdown/core.py", line 264, in convert
        root = self.parser.parseDocument(self.lines).getroot()
      File "/home/sean/.local/lib/python3.10/site-packages/markdown/blockparser.py", line 90, in parseDocument
        self.parseChunk(self.root, '\n'.join(lines))
      File "/home/sean/.local/lib/python3.10/site-packages/markdown/blockparser.py", line 105, in parseChunk
        self.parseBlocks(parent, text.split('\n\n'))
      File "/home/sean/.local/lib/python3.10/site-packages/markdown/blockparser.py", line 123, in parseBlocks
        if processor.run(parent, blocks) is not False:
      File "/home/sean/.local/lib/python3.10/site-packages/markdown/blockprocessors.py", line 193, in run
        self.parser.parseBlocks(sibling, [block])
      File "/home/sean/.local/lib/python3.10/site-packages/markdown/blockparser.py", line 123, in parseBlocks
        if processor.run(parent, blocks) is not False:
      File "/home/sean/.local/lib/python3.10/site-packages/pymdownx/superfences.py", line 983, in run
        blocks[0] = self.revert_greedy_fences(blocks[0])
      File "/home/sean/.local/lib/python3.10/site-packages/pymdownx/superfences.py", line 958, in revert_greedy_fences
        original, pos = self.extension.stash.get(key)
    TypeError: cannot unpack non-iterable NoneType object
    ```
    </details>

1. The error can be fixed by taking _either_ of the following actions:

    - Modify `mkdocs.yml`, removing `pymdownx.superfences`. It would become:

        ```yml
        site_name: Foo
        ```

    - Modify `docs/index.md`, fixing the indentation to become:

        ```md
        1. Foo
            <details>
              <summary>Summary 1</summary>
          
                Content 1
            </details>
            <details>
              <summary>Summary 2</summary>
          
                Content 2
            </details>
        ```

### Version(s) & System Info

- Ubuntu 22.04
- Python 3.10
- `pymdown-extensions`: 9.9 (as installed by [mkdocs-material](https://github.com/squidfunk/mkdocs-material)).

**Comment by facelessuser** [comment]
Yep, we should handle this gracefully. It sees a bad placeholder due to the Markdown adding a placeholder, so it tries to see if the placeholder is a fence it converted (which in this case it isn't), but our default output when a placeholder isn't in our stash doesn't match the signature of the expected output.

@gir-bot remove S: triage
